ALTER TABLE "Clan" ADD COLUMN IF NOT EXISTS "isNoRaid" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ClanFlagOption" ADD COLUMN IF NOT EXISTS "category" TEXT NOT NULL DEFAULT 'MOD';
ALTER TABLE "ClanFlagOption" ADD COLUMN IF NOT EXISTS "shared" BOOLEAN NOT NULL DEFAULT false;
DROP INDEX IF EXISTS "Clan_selectedFlagId_key";
CREATE INDEX IF NOT EXISTS "Clan_selectedFlagId_idx" ON "Clan"("selectedFlagId");
