const { baseEmbed } = require('../utils/embeds');
function buildLaunchSchedulePanel() {
 const main=baseEmbed().setColor(0xd4af37).setTitle('🚀 LANÇAMENTO OFICIAL • CHAMPIONS Z').setDescription(['📅 **ABERTURA DO SERVIDOR: 03/10/2026**','','O CHAMPIONS Z abre as portas em **3 de outubro de 2026**.','O primeiro mês será de preparação: explore Chernarus, faça loot, conheça as novas áreas, monte seu clã e fortaleça sua base.','','🏆 **AS COMPETIÇÕES OFICIAIS COMEÇAM EM 03/11/2026**','Até essa data, os jogadores terão **1 mês inteiro para se estabelecer**. Eventos que valem pontos para a temporada competitiva só começam em **3 de novembro de 2026**.','','⚔️ **CLÃS: até 10 jogadores**','💰 **Premiação da temporada: mais de R$ 3.000 em PIX e recompensas**','🎯 Servidor competitivo • 1ª pessoa • Chernarus • sem Pay-to-Win'].join('\n')).setFooter({text:'CHAMPIONS Z • NOVA ERA • 03/10/2026'});
 const raids=baseEmbed().setColor(0xe53935).setTitle('💣 CRONOGRAMA DE RAID').setDescription(['🟡 **03/10/2026 — LANÇAMENTO**','Começa a fase inicial de preparação do servidor.','','🟠 **10/10/2026 — RAID POR FALHA LIBERADA**','Uma semana após o lançamento, passa a valer a modalidade de raid por falha conforme as regras oficiais do servidor.','','🔴 **17/10/2026 — RAID GERAL LIBERADA**','Duas semanas após o lançamento começa a raid geral.','','💥 A partir de **17/10/2026**, **TODO SÁBADO É DIA DE RAID**.','**Tiro, porrada e bomba.** As raids devem sempre respeitar as regras oficiais publicadas pela administração.'].join('\n')).setFooter({text:'CHAMPIONS Z • CRONOGRAMA OFICIAL DE RAID'});
 const season=baseEmbed().setColor(0x1565ff).setTitle('🏆 TEMPORADA • COMPETIÇÃO E BANDEIRA BRANCA').setDescription(['🏁 **03/11/2026 — INÍCIO OFICIAL DA COMPETIÇÃO**','A partir desta data começam os eventos e disputas que contam pontos para a temporada.','','🏳️ **BANDEIRA BRANCA PARA CLÃ NOVO**','Depois do início da competição, todo **clã novo que entrar durante a temporada** terá direito a **14 dias de Bandeira Branca** para conseguir se estabelecer.','','Durante esses 14 dias:','• o clã protegido **não pode receber raid**;','• o clã protegido **também não pode raidar outros clãs**;','• ao terminar os 14 dias, a proteção acaba e o clã entra normalmente no ciclo competitivo e de raids.','','⚠️ A Bandeira Branca é uma proteção de entrada na temporada, não uma vantagem ofensiva.'].join('\n')).setFooter({text:'CHAMPIONS Z • TEMPORADA OFICIAL A PARTIR DE 03/11/2026'});
 const features=baseEmbed().setColor(0x2ecc71).setTitle('🧟 O QUE VOCÊ ENCONTRA NO CHAMPIONS Z').setDescription(['• **Chernarus em 1ª pessoa** com foco competitivo','• **Clãs de até 10 jogadores**','• **10 novas áreas militares** com loot especial','• **2 bunkers** com progressão e itens necessários','• **Plane Crash / Plane Drop** com containers e chave','• KOTH, Mega KOTH e outros eventos','• Ranking de jogadores e clãs por temporada','• Sistema de vínculo Discord ↔ Steam','• Anti-cheat e verificações surpresa','• **Sem Pay-to-Win**','• Premiações em **PIX** e recompensas durante a temporada'].join('\n')).setFooter({text:'CHAMPIONS Z • SOBREVIVA • COMPITA • VENÇA'});
 return [{embeds:[main],legacyTitles:['🚀 LANÇAMENTO CHAMPIONS Z']},{embeds:[raids]},{embeds:[season]},{embeds:[features]}];
}
module.exports={buildLaunchSchedulePanel};
